site_name: VRee SDK for Unity
nav:
  - Home: index.md
  - "Getting Started":
      - Getting Started: getting-started.md
      - VRee License: vree-license.md
      - VRee Settings: vree-settings.md
      - User Interface: user-interface.md
  - "Customize":
      - Networking: networking.md
      - Object Synchronization: object-synchronization.md
      - Player: vree-player.md
      - Adapters: adapters.md
      - "Custom scripts":
          - VReeMonoBehaviour: vree-monobehaviour.md
  - FAQ: FAQ.md
  - Troubleshooting: troubleshooting.md

theme: readthedocs

markdown_extensions:
  - footnotes
